### ISSUE TITLE
Screenwipe problems

### ISSUE THREAD

**Issue by jeffellenbogen** [jeffellenbogen/rects#1]
ScreenWipe() is clearing the screen before completing the horizontal, vertical, or diagonal wipes. Can't identify the reason the screen clears to black before wipe begins...

<a href = "https://photos.app.goo.gl/fDirXcLhJmiJLKJz6" target="new">Video of problem</a>

**Comment by gsalaman** [comment]
Hmmm...your octocats are referenced with "image", while the wipe functions are referenced by "temp_image".   What happens if you change newImage() to use "temp_image" rather than "image"?  You also may have to get rid of the "Image.new" at the beginning of "ScreenWipe()" as that will probably also clear out the octocat.  Just draw your new lines over the octocat import...

**Comment by jeffellenbogen** [comment]
Glenn solved this issue using the .paste method from PIL library.
